on: deployment_status
jobs:
  publish:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: html to pdf
      uses: markwilson/html2pdf@v1.0
      with:
        htmlPath: 'https://dorkside.github.io/markdown-cv/index.html'
        pdfName: 'test'
