on: deployment_status
jobs:
  publish:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: https://dorkside.github.io/markdown-cv/index.html
        outputFile: ./public/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
