on: deployment_status
jobs:
  publish:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: html to pdf
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://www.noenieto.com/resume/
        outputFile: ./public/resume.pdf
        usePuppeteer: true
        useScreen: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
